##  Dataframes Fundamentals
> Este notebook está desarrollado por Mg. Ing. Layla Scheli

##![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) spark.createDataFrame()

> Función que te permite crear dataframes

In [ ]:
df=  [{'nombre': 'Layla', 'edad': 30 , 'ciudad': 'Rosario' },
      {'nombre': 'Jose', 'edad': 30 , 'ciudad': 'Lima'},
      {'nombre': 'Juan', 'edad': 20 , 'ciudad': 'cdmx'}]

dfCustomer=spark.createDataFrame(df)

##![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) count()

> Retorna el nro. de filas del dataset

In [ ]:
dfCustomer.count()

##![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) printSchema()

> Función que que devuelve la estructura del dataframe

In [ ]:
dfCustomer.printSchema()

##![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) show(..)

Esta función me permite visualizar los datos

Parámetros opcionales:
* **n**: Número de filas que queremos visualizar.
* **truncate**: Si el valor es en True, las columnas de más de 20 caracteres serán omitidos

In [ ]:
dfCustomer.show(2)

##![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) display(..)

Podemos utilizar tambien la función display para la visualización de datos y ver los datos de otra manera

In [ ]:
display(dfCustomer)

ciudad,edad,nombre
Rosario,28,Layla
Lima,30,Jose
Medellin,20,Juan

##![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) limit(..)

La principal diferencia entre display y show , es que en show podemos indicarle el nro. de filas

> Esta función me permite crear un nuevo dataset donde le pueda colocar un límite de filas

In [ ]:
dfCustomerLimit = dfCustomer.limit(2) 

dfCustomerLimit.show()

##![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) select(..)

Esta función te permite seleccionar algunas columnas de un datfrme

In [ ]:
# Transformamos la data, quedandonos solo con 2 columnas
dfCustomerSelect = (dfCustomer
  .select("nombre","edad") 
)
# Imprimimos el schema
dfCustomerSelect.printSchema()

#Visualizamos por pantalla
dfCustomerSelect.show()

##![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) drop(..)

La función drop() te permite eliminar columnas de un dataframe

In [ ]:
dfCustomerDrop= dfCustomer.drop("edad")

dfCustomerDrop.show()